class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.58.tar.gz"
  sha256 "193ce01296c16c68a6b7452cfe9e1071c390c6486696a8585a4702ce99b626f0"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "fb9592350c9bacb8df2abc91448ac1f9c3e4f9498dcb79b76b9f7363b3b2218c"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "fb9592350c9bacb8df2abc91448ac1f9c3e4f9498dcb79b76b9f7363b3b2218c"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "fb9592350c9bacb8df2abc91448ac1f9c3e4f9498dcb79b76b9f7363b3b2218c"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "c592183a2f6223ae981ff52a36f74a64ce770a11b9279be30f36f8db9141f886"
    sha256 cellar: :any,                 x86_64_linux:      "4c9c61a62d49729aaacf53a13075a5ade591784bc4248b8e22364ac14d3c8cf8"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
